spring:
  application:
    name: employee-management
  profiles:
    active: dev
  cache:
    type: caffeine
    cache-names:
      - employeeReports
    caffeine:
      spec: expireAfterWrite=60s,maximumSize=100

logging:
  level:
    root: info
    com.example.employeemanagement: info

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: never
