spring:
  application:
    name: employee-management
  profiles:
    active: dev

logging:
  level:
    root: info
    com.example.employeemanagement: info

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: never
